Repository ilosaurus/attack-defense-docker-series, pull requests merged in 2020-10, with the labels that each got.

#4 update write up misconfigured docker socket
  01-write-up-insecure-docker-registry-II.md
  02-write-up-docker-misconfigured-socket.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, help wanted

#5 update write up misconfigured docker socket part 02
  02-write-up-docker-misconfigured-socket.md
Labels: documentation, enhancement, hacktoberfest-accepted, help wanted

#7 update 03-write-ups-priv-escalation-1
  03-write-up-docker-priv-escal-I.md
  files/img/01.jpg
  files/img/02.jpg
  files/img/03.jpg
  files/img/04.jpg
  files/img/05.jpg
  files/img/06.jpg
  files/img/07.jpg
  files/img/08.jpg
  files/img/09.jpg
  files/img/10.jpg
  files/img/11.jpg
  files/img/11b.jpg
  files/img/11c.jpg
  files/img/12.jpg
  files/img/13.jpg
  files/img/14.jpg
Labels: enhancement, good first issue, hacktoberfest-accepted, help wanted

#8 update outline readme.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, help wanted

#9 add scrips section
  scripts/01-cleanup.md
Labels: enhancement, hacktoberfest-accepted, help wanted

#10 add clean up script
  scripts/clean-up.sh
Labels: bug, enhancement, hacktoberfest-accepted, help wanted
